### ISSUE TITLE
Getting size limit error.

### ISSUE THREAD

**Issue by deswaraj** [CrunchyData/openshift-postgres-cartridge#1]
The cartridge manifest at 'https://github.com/CrunchyData/openshift-postgres-cartridge' could not be downloaded: The cartridge manifest at 'https://github.com/CrunchyData/openshift-postgres-cartridge' must be smaller than 20480 bytes.

![image](https://cloud.githubusercontent.com/assets/968885/6426603/f8423916-bf89-11e4-9003-44450efd4caa.png)

**Comment by jmccormick2001** [comment]
use this URL when adding the cartridge to your app:

http://cartreflect-claytondev.rhcloud.com/github/CrunchyData/openshift-postgres-cartridge

I just tested this with a php app, added the crunchy pg cartridge to it using the above URL and it worked .  Let me know if you have problems with this.  regards.

**Comment by deswaraj** [comment]
yes it installs PostgreSQL.

I am unable to create these extension.

-- Enable PostGIS (includes raster)
CREATE EXTENSION postgis;
-- Enable Topology
CREATE EXTENSION postgis_topology;
-- fuzzy matching needed for Tiger
CREATE EXTENSION fuzzystrmatch;
-- Enable US Tiger Geocoder
CREATE EXTENSION postgis_tiger_geocoder;
