### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by sebastianjonas** [CrunchyData/openshift-postgres-cartridge#2]
I tried to add this cartridge to my ruby app in openshift.
The command:
rhc cartridge add -a ruby http://cartreflect-claytondev.rhcloud.com/github/crunchydata/openshift-postgres-cartridge

The error:
The cartridge manifest at 'http://cartreflect-claytondev.rhcloud.com/github/crunchydata/openshift-postgres-cartridge' was not available (status code: 400).

**Comment by abrightwell** [comment]
@sebastianjonas - thanks for the heads up, we will look in to it.

**Comment by jmccormick2001** [comment]
I just tested it from the Openshift Online web UI, and it still works.
Unfortunately this "internet coffee bar" on Curacao doesn't allow me to
install and run the 'rhc' client application this user is referring to.

On RHEL or Centos, you can 'yum install rhc' if I recall to install the
client.  You will need to register for a free Openshift Online
account to try this command out.

cheers

**Comment by sebastianjonas** [comment]
Well it worked now :) Seemed to be a temporary problem.
